# HTTP-specific options.
server:
  type: simple
  rootPath: /api/
  applicationContextPath: /
  adminContextPath: /admin
  connector:
    type: http
    port: 8080

  requestLog:
    appenders:
      - type: console
        timeZone: UTC
        target: stdout


logging:
  level: WARN
  loggers:
    "com.smoketurner.dropwizard.graphql": DEBUG
    "io.dropwizard": DEBUG
    "org.hibernate.SQL":
      level: WARN
      additive: false

graphql:
  enableTracing: true
  queryCache: maximumSize=10000
  schemaFiles:
    - schema.graphql

database:
  # the name of your JDBC driver
  driverClass: org.postgresql.Driver

  # the username
  user: pg-user

  # the password
  password: iAMs00perSecrEET

  # the JDBC URL
  url: jdbc:postgresql://0.0.0.0:5432/db

  # any properties specific to your JDBC driver:
  properties:
    charSet: UTF-8
    hibernate.dialect: org.hibernate.dialect.PostgreSQLDialect

  # the maximum amount of time to wait on an empty pool before throwing an exception
  maxWaitForConnection: 1s

  # the SQL query to run when validating a connection's liveness
  validationQuery: "/* MyApplication Health Check */ SELECT 1"

  # the minimum number of connections to keep open
  minSize: 8

  # the maximum number of connections to keep open
  maxSize: 32

  # whether or not idle connections should be validated
  checkConnectionWhileIdle: false